create table Acronimo (id  bigserial not null, name varchar(5), primary key (id));
create table Arqueologo (id  bigserial not null, name varchar(60), primary key (id));
create table Bio (id  bigserial not null, arqueologo boolean, genetica boolean, isotopos boolean, morfologia boolean, paleopatologia boolean, registro varchar(255), completitud_id int8, edad_id int8, preservacion_id int8, sexo_id int8, primary key (id));
create table Completitud (id  bigserial not null, name varchar(5), primary key (id));
create table Edad (id  bigserial not null, name varchar(5), primary key (id));
create table Ente (id  bigserial not null, name varchar(60), primary key (id));
create table Enterramiento (id  bigserial not null, name varchar(60), primary key (id));
create table Excavacion (id  bigserial not null, periodo varchar(20), arqueologo_id int8, ente_id int8, enterramiento_id int8, posicion_id int8, sepultura_id int8, primary key (id));
create table Forma (id  bigserial not null, name varchar(10), primary key (id));
create table Ingreso (id  bigserial not null, egreso timestamp, ingreso timestamp, almaceno_id int8, digitalizo_id int8, forma_id int8, registro_id int8, resto_id int8, primary key (id));
create table Io (id  bigserial not null, bibliografia TEXT, museo varchar(5), bio_id int8, excavacion_id int8, ingreso_id int8, ubicacion_id int8, yacimiento_id int8, primary key (id));
create table Localidad (id  bigserial not null, name varchar(60), primary key (id));
create table Pais (id  bigserial not null, name varchar(60), primary key (id));
create table Posicion (id  bigserial not null, name varchar(60), primary key (id));
create table Preservacion (id  bigserial not null, name varchar(60), primary key (id));
create table Provincia (id  bigserial not null, name varchar(60), primary key (id));
create table Resto (id  bigserial not null, name varchar(10), primary key (id));
create table Sepultura (id  bigserial not null, name varchar(60), primary key (id));
create table Sexo (id  bigserial not null, name varchar(1), primary key (id));
create table Sitio (id  bigserial not null, name varchar(60), primary key (id));
create table Ubicacion (id  bigserial not null, caja varchar(5), estanteria varchar(5), informes boolean, plano varchar(5), sala varchar(5), primary key (id));
create table Yacimiento (id  bigserial not null, coordenadas varchar(50), acronimo_id int8, localidad_id int8, pais_id int8, provincia_id int8, sitio_id int8, primary key (id));
alter table Bio add constraint FK_i29beteci9cxwqbkwqe0gqstf foreign key (completitud_id) references Completitud;
alter table Bio add constraint FK_mmkpgave1gh6825iem1bsyyh0 foreign key (edad_id) references Edad;
alter table Bio add constraint FK_83saun99aspny8qsc3tf0l94g foreign key (preservacion_id) references Preservacion;
alter table Bio add constraint FK_ixy4wdccm4eheiq3n26elm2ic foreign key (sexo_id) references Sexo;
alter table Excavacion add constraint FK_my8v55mj1mae7ts2s9jejljtq foreign key (arqueologo_id) references Arqueologo;
alter table Excavacion add constraint FK_bhe4mppmujrsjavkq2aqlfm3p foreign key (ente_id) references Ente;
alter table Excavacion add constraint FK_gbvm1ilnohitykkx7p73v5gi6 foreign key (enterramiento_id) references Enterramiento;
alter table Excavacion add constraint FK_9pp19elx8iijp0t2a23o67ags foreign key (posicion_id) references Posicion;
alter table Excavacion add constraint FK_s43jppr6bykk46qxprjho97s1 foreign key (sepultura_id) references Sepultura;
alter table Ingreso add constraint FK_fm5ohk7mbcbn0wlcbqypbbewj foreign key (almaceno_id) references Arqueologo;
alter table Ingreso add constraint FK_d4rsumrbj62jlrd5jctx8au9y foreign key (digitalizo_id) references Arqueologo;
alter table Ingreso add constraint FK_rxawt88gswfniqh63vyx8qh58 foreign key (forma_id) references Forma;
alter table Ingreso add constraint FK_a8aqw4559bpkbvadqo88sowhf foreign key (registro_id) references Arqueologo;
alter table Ingreso add constraint FK_41t5p3y1855qu689nhum3sn21 foreign key (resto_id) references Resto;
alter table Io add constraint FK_3be7w1txveqdv4d4vljafhp72 foreign key (bio_id) references Bio;
alter table Io add constraint FK_6a8072hd23b47250s12wiwqx4 foreign key (excavacion_id) references Excavacion;
alter table Io add constraint FK_qt5tw0tw8in53tkny10dnvsvg foreign key (ingreso_id) references Ingreso;
alter table Io add constraint FK_lxah6kh0f2ag81vq3ajox3yw5 foreign key (ubicacion_id) references Ubicacion;
alter table Io add constraint FK_trojgaokgnt9xtjcgbudbcsgm foreign key (yacimiento_id) references Yacimiento;
alter table Yacimiento add constraint FK_qkub5hcynl2bpy3xj58884s6y foreign key (acronimo_id) references Acronimo;
alter table Yacimiento add constraint FK_cu1omfnylucjgxc7g0484iqph foreign key (localidad_id) references Localidad;
alter table Yacimiento add constraint FK_jcjatpq7tt2xgm44yhia304se foreign key (pais_id) references Pais;
alter table Yacimiento add constraint FK_p8dqqoeeei5v8ulhhllm9envp foreign key (provincia_id) references Provincia;
alter table Yacimiento add constraint FK_fkr33f2hyu50vmy0isboj9c77 foreign key (sitio_id) references Sitio;
